### ISSUE TITLE
MultipleDemo couldn't detect different type kinect

### ISSUE THREAD

**Issue by sewonist** [AS3NUI/airkinect-2-examples#2]
I’ve tested multiple kinect support. 
Unfortunately, It didn’t work.
I checked start event.
Probably, DeviceEvent.STARTED event occurred at one device. 
But, DeviceEvent.STOPPED event occurred both. 
I tested with X-Box kincet and MS kincet.

**Comment by aphex** [comment]
This issue will be tracked here, https://github.com/AS3NUI/airkinect-2-core/issues/2
