### ISSUE TITLE
GripReleaseExample

### ISSUE THREAD

**Issue by luisrodriguezmartinez** [AS3NUI/airkinect-2-examples#7]
Hello to try these I asked

com.as3nui.nativeExtensions.air.kinect.frameworks.mssdk.MSKinect.as

So I downloaded it from here:

https://github.com/AS3NUI/airkinect-2-core/tree/master/as3/src/com/as3nui/nativeExtensions/air/kinect/frameworks/mssdk/data

But now I'm trying to prove GripReleaseExample.as not working properly

http://www.screenr.com/l3pH

**Comment by wouterverweirder** [comment]
The hand grab / release is only in our dev branch right now (examples & core). Make sure you have our dev branch versions of the ane & examples, and you have installed the latest version of the MS SDK.
